<template>
  <!-- @ts-ignore -->
  <div class="konsta-class-scanner">
    <span class="!h-auto !ms-0 -end-1.5 -left-4.75 -m-0.5 -m-1 -mb-2 -mb-2.5"></span>
    <span class="-mb-6 -me-2 -ml-2 -mr-2 -ms-2 -ms-3 -mt-2.5 -mt-3"></span>
    <span class="-mt-4 -mt-5.5 -mt-6 -mx-2 -my-1 -my-2 -rotate-90 -top-0.5"></span>
    <span class="-top-1 -top-2 -top-4.75 -translate-x-1/2 -translate-x-2 -translate-x-full -translate-y-1/2 -translate-y-20"></span>
    <span class="-translate-y-full -z-10 [&>*]:no-safe-areas-left [&>*]:no-safe-areas-right absolute active:bg-black/10 active:bg-ios-primary-shade active:bg-primary/15"></span>
    <span class="active:bg-primary/25 active:duration-0 active:fill-stone-200 active:hairline-transparent active:not-[:has(.k-toggle:active)]:bg-black/10 active:opacity-100 active:opacity-20 active:opacity-30"></span>
    <span class="active:opacity-50 active:opacity-55 active:range-thumb:scale-150 active:shadow-lg align-middle appearance-none aspect-square backdrop-blur-[2px]"></span>
    <span class="backdrop-blur-lg before:align-middle before:bg-md-light-on-surface-variant before:dark:bg-md-dark-on-surface-variant before:h-0.75 before:inline-block before:me-1 before:rounded-full"></span>
    <span class="before:w-0.75 bg-[#e5e5ea] bg-black bg-black/10 bg-black/15 bg-black/20 bg-black/5 bg-black/50"></span>
    <span class="bg-cover bg-current bg-gradient-to-b bg-gradient-to-t bg-ios-light-glass bg-ios-light-surface bg-ios-light-surface-1 bg-ios-light-surface-1-shade"></span>
    <span class="bg-ios-light-surface-variant bg-md-light-on-primary bg-md-light-outline bg-md-light-primary bg-md-light-primary-container bg-md-light-primary/30 bg-md-light-secondary-container bg-md-light-surface"></span>
    <span class="bg-md-light-surface-1 bg-md-light-surface-2 bg-md-light-surface-3 bg-md-light-surface-5 bg-md-light-surface-variant bg-primary bg-primary/15 bg-transparent"></span>
    <span class="bg-white block border border-2 border-b border-black/10 border-black/20 border-black/30"></span>
    <span class="border-collapse border-l border-md-dark-outline border-md-light-on-surface border-md-light-outline border-md-light-primary border-none border-primary"></span>
    <span class="border-red-500 border-t border-transparent bottom-0 bottom-0.5 bottom-1 bottom-full bottom-safe-2"></span>
    <span class="bottom-safe-4 box-border break-words contents cursor-pointer dark:active:bg-white/10 dark:active:bg-white/5 dark:active:fill-stone-700"></span>
    <span class="dark:active:not-[:has(.k-toggle:active)]:bg-white/10 dark:bg-[#252525] dark:bg-[#323234] dark:bg-black dark:bg-ios-dark-glass dark:bg-ios-dark-surface dark:bg-ios-dark-surface-1 dark:bg-ios-dark-surface-1-tint"></span>
    <span class="dark:bg-ios-dark-surface-variant dark:bg-ios-primary-shade/50 dark:bg-md-dark-on-primary dark:bg-md-dark-outline dark:bg-md-dark-primary dark:bg-md-dark-primary-container dark:bg-md-dark-primary/30 dark:bg-md-dark-secondary-container"></span>
    <span class="dark:bg-md-dark-surface dark:bg-md-dark-surface-1 dark:bg-md-dark-surface-2 dark:bg-md-dark-surface-3 dark:bg-md-dark-surface-5 dark:bg-md-dark-surface-variant dark:bg-primary dark:bg-primary/10"></span>
    <span class="dark:bg-transparent dark:bg-white dark:bg-white/10 dark:bg-white/15 dark:bg-white/20 dark:bg-white/75 dark:border-md-dark-on-surface dark:border-md-dark-outline"></span>
    <span class="dark:border-md-dark-primary dark:border-white/10 dark:border-white/15 dark:border-white/20 dark:border-white/30 dark:divide-md-dark-outline dark:fill-md-dark-primary dark:fill-stone-500"></span>
    <span class="dark:from-ios-dark-surface/50 dark:hover:bg-md-dark-secondary-container dark:hover:bg-white/10 dark:placeholder-md-dark-on-surface-variant dark:placeholder-whit/40 dark:placeholder-white/30 dark:shadow-[0_0_40px_15px] dark:shadow-ios-dark-glass"></span>
    <span class="dark:shadow-ios-dark-glass-fab dark:shadow-ios-dark-glass-thumb dark:shadow-primary dark:shadow-primary/50 dark:text-black dark:text-md-dark-on-primary dark:text-md-dark-on-primary-container dark:text-md-dark-on-secondary-container"></span>
    <span class="dark:text-md-dark-on-surface dark:text-md-dark-on-surface-variant dark:text-md-dark-primary dark:text-white dark:text-white/30 dark:text-white/45 dark:text-white/55 dark:text-white/60"></span>
    <span class="dark:text-white/90 dark:touch-ripple-primary dark:touch-ripple-white divide-black/10 divide-md-light-outline divide-primary divide-x duration-0"></span>
    <span class="duration-100 duration-200 duration-300 duration-400 duration-500 duration-600 duration-[600ms] ease-material-in"></span>
    <span class="ease-material-in-popup end-0 end-2 end-4 fill-black fill-primary fill-stone-400 first:border-r"></span>
    <span class="first:border-r-0 first:mt-0 first:mt-2 first:mx-2 first:mx-4 first:px-6 first:rounded-lg-s first:rounded-s"></span>
    <span class="first:rounded-t-4xl fixed flex flex-col flex-row focus:outline-none font-bold font-medium"></span>
    <span class="font-normal font-semibold from-ios-light-surface gap-1 gap-2 gap-3 gap-4 group"></span>
    <span class="group-active:bg-transparent group-active:opacity-100 group-active:scale-[0.75] group-active:scale-[1.1] group-active:scale-[1.4] group-has-[input:active]/range:bg-transparent group-has-[input:active]/range:opacity-100 group-has-[input:active]/range:scale-50"></span>
    <span class="group-has-[input:active]/range:scale-[1.4] group-has-[input:active]/range:scale-x-50 group/range group/toolbar-pane h-0.25 h-0.5 h-1 h-1.5"></span>
    <span class="h-10 h-11 h-12 h-13 h-14 h-16 h-2.5 h-20"></span>
    <span class="h-3 h-3.5 h-4 h-4.5 h-5 h-5.5 h-6 h-6.5"></span>
    <span class="h-7 h-8 h-8.5 h-[1em] h-[5.5rem] h-full h-px h-screen"></span>
    <span class="hairline-b hairline-t hidden hover:bg-black/5 hover:bg-md-light-secondary-container inline-block inline-flex inset-0"></span>
    <span class="inset-1 inset-1/2 inset-y-0 ios items-center items-start items-stretch justify-between"></span>
    <span class="justify-center justify-end justify-start k-actions k-actions-button k-actions-group k-app k-block"></span>
    <span class="k-block-footer k-block-header k-block-title k-breadcrumbs k-breadcrumbs-item k-breadcrumbs-separator k-button k-card"></span>
    <span class="k-checkbox k-chip k-dialog k-fab k-ios k-ios-preloader k-link k-list"></span>
    <span class="k-list-button k-list-input k-list-item k-material k-material-preloader k-message k-messagebar k-messages"></span>
    <span class="k-messages-title k-navbar k-navbar-back-link k-notifications k-page k-panel k-popover k-popup"></span>
    <span class="k-preloader k-progressbar k-radio k-range k-searchbar k-segmented k-segmented-strong-button-active k-sheet"></span>
    <span class="k-tabbar-link-active k-tabbar-link-icon k-table k-toast k-toggle k-toolbar k-toolbar-pane k-touch-ripple-inset"></span>
    <span class="last-child-hairline-b-none last:hairline-transparent last:rounded-b-4xl last:rounded-e last:rounded-lg-e leading-4 leading-none leading-tight"></span>
    <span class="left-0 left-1/2 left-4 left-4.75 left-full left-safe left-safe-4 line-clamp-2"></span>
    <span class="m-0 mask-b-from-50% mask-b-to-100% mask-t-from-50% mask-t-to-100% material max-h-12 max-h-full"></span>
    <span class="max-w-[66%] max-w-[70%] max-w-[90%] max-w-full max-w-lg max-w-md mb-0.5 mb-12"></span>
    <span class="mb-16 mb-2 mb-8 md:-ms-[284px] md:end-auto md:h-160 md:min-w-12 md:min-w-24"></span>
    <span class="md:no-safe-areas md:px-8 md:rounded-4xl md:rounded-[1.75rem] md:start-1/2 md:w-160 md:w-[568px] md:w-auto"></span>
    <span class="me-1 me-1.5 me-2 me-3 me-4 min-h-4 min-h-5 min-h-7"></span>
    <span class="min-h-[3.5rem] min-h-[56px] min-h-screen min-w-12 min-w-4 min-w-5 ml-10 ml-4"></span>
    <span class="ml-safe-2 ml-safe-4 mr-4 mr-safe-2 mr-safe-4 ms-1 ms-2 ms-3"></span>
    <span class="ms-4 ms-auto mt-0.5 mt-1 mt-2 mt-2.5 mt-4 mt-8"></span>
    <span class="mx-1 mx-safe-4 my-4 my-8 no-safe-areas no-safe-areas-left no-safe-areas-right no-scrollbar"></span>
    <span class="not-italic opacity-0 opacity-100 opacity-20 opacity-35 opacity-45 opacity-50 opacity-75"></span>
    <span class="opacity-80 opacity-85 origin-bottom origin-left outline-offset-0 overflow-auto overflow-hidden overflow-visible"></span>
    <span class="p-0 p-0.5 p-1 p-3.5 p-4 p-6 pb-1 pb-2"></span>
    <span class="pb-3 pb-3.5 pb-4 pb-safe pb-safe-4 pe-2 pe-4 pe-safe-4"></span>
    <span class="pl-10.5 pl-4 pl-6 pl-safe pl-safe-2 pl-safe-4 pl-safe-8 placeholder-black/30"></span>
    <span class="placeholder-md-light-on-surface-variant placeholder-transparent pointer-events-auto pointer-events-none pr-4 pr-6 pr-9 pr-safe"></span>
    <span class="pr-safe-2 pr-safe-4 pr-safe-8 ps-1 ps-12 ps-2 ps-4 ps-safe-4"></span>
    <span class="pt-0 pt-2 pt-3 pt-4 pt-6 pt-safe px-0 px-0.5"></span>
    <span class="px-1.5 px-2 px-3 px-4 px-7 px-safe-2 px-safe-4 py-0"></span>
    <span class="py-0.5 py-1 py-1.5 py-2 py-2.5 py-3 py-3.5 py-4"></span>
    <span class="py-5 range-thumb:-mt-1.5 range-thumb:-mt-3 range-thumb:appearance-none range-thumb:border-none range-thumb:h-11 range-thumb:h-6 range-thumb:opacity-0"></span>
    <span class="range-thumb:transform range-thumb:w-1 range-thumb:w-9.5 range-track:appearance-none range-track:h-px received relative resize-none"></span>
    <span class="right-0 right-1.5 right-full right-safe right-safe-4 rotate-0 rotate-45 rotate-90"></span>
    <span class="rounded rounded-2xl rounded-3xl rounded-4xl rounded-[1.75rem] rounded-[inherit] rounded-e rounded-e-full"></span>
    <span class="rounded-e-lg rounded-full rounded-l-2xl rounded-l-md rounded-lg rounded-md rounded-r-2xl rounded-s"></span>
    <span class="rounded-s-full rounded-s-lg rounded-sm rounded-t rounded-t-2xl rounded-t-4xl rounded-xl rtl:!-translate-x-5"></span>
    <span class="rtl:!-translate-x-5.5 rtl:divide-x-reverse rtl:first:border-l rtl:first:border-r rtl:first:border-r-0 rtl:first:border-r-2 rtl:last:border-r-0 rtl:origin-right"></span>
    <span class="rtl:rotate-180 rtl:translate-x-1/2 safe-areas scale-0 scale-100 scale-133 scale-140 scale-50"></span>
    <span class="scale-[0.666] scale-[0.85] scale-x-90 scale-x-[0.5] scale-y-75 scale-y-[2] select-none self-center"></span>
    <span class="self-end sent shadow shadow-[0_0_40px_10px] shadow-ios-light-glass shadow-ios-light-glass-thumb shadow-ios-thumb shadow-primary/75"></span>
    <span class="shrink shrink-0 shrink-1 size-6 sm:px-4 sm:px-6 sm:py-3 sm:py-3.5"></span>
    <span class="sr-only start-0 start-0.5 start-1 start-2 start-4 sticky table"></span>
    <span class="text-2xs text-[0.875rem] text-[1.25rem] text-[1.375rem] text-[15px] text-[17px] text-[1rem] text-black"></span>
    <span class="text-black/30 text-black/45 text-black/55 text-black/60 text-black/90 text-center text-current text-inherit"></span>
    <span class="text-left text-md-light-on-primary text-md-light-on-primary-container text-md-light-on-secondary-container text-md-light-on-surface text-md-light-on-surface-variant text-md-light-primary text-primary"></span>
    <span class="text-red-500 text-sm text-start text-white text-xl text-xs textarea to-transparent"></span>
    <span class="top-0 top-0.5 top-1 top-1/2 top-4.75 top-full top-safe-15 top-safe-16"></span>
    <span class="top-safe-2 top-safe-4 touch-none touch-pan-y touch-ripple-black touch-ripple-primary touch-ripple-white transform"></span>
    <span class="transform-gpu transition transition-all transition-colors transition-transform translate-3d translate-x-10.5 translate-x-2"></span>
    <span class="translate-x-5 translate-x-5.5 translate-x-8 translate-x-full translate-y-3 translate-y-4 translate-y-6 translate-y-8"></span>
    <span class="translate-y-full translate-z-0 truncate uppercase w-0.5 w-1 w-10 w-11"></span>
    <span class="w-12 w-13 w-14 w-16 w-3 w-3.5 w-3/4 w-4"></span>
    <span class="w-4.5 w-5 w-5.5 w-6 w-6.5 w-60 w-7 w-72"></span>
    <span class="w-75 w-78 w-8 w-9.5 w-auto w-full w-px w-screen"></span>
    <span class="whitespace-nowrap z-1 z-10 z-20 z-30 z-40 z-50"></span>
  </div>
</template>
<script>
export default { name: "KonstaClassScanner" };
</script>
